apiVersion: mcpshield.io/v1alpha1
kind: McpServer
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  # TODO(user): Add fields here
